/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package premiereinterfacegraphique;

/**
 *
 * @author Soso
 */
public class Fenetreprincipale extends javax.swing.JFrame {

    /**
     * Creates new form Fenetreprincipale
     */
    public Fenetreprincipale() {
        initComponents();
        Cocabouton.setVisible(false);
        IceTeaBouton.setVisible(false);
        OasisBouton.setVisible(false);
        ValidationAchat.setVisible(false);
        SUIVANT.setVisible(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonvalidation = new javax.swing.JButton();
        zonenom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        texteresultat = new javax.swing.JLabel();
        textselectionachat = new javax.swing.JLabel();
        Cocabouton = new javax.swing.JRadioButton();
        OasisBouton = new javax.swing.JRadioButton();
        IceTeaBouton = new javax.swing.JRadioButton();
        Panier = new javax.swing.JLabel();
        ValidationAchat = new javax.swing.JButton();
        SUIVANT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boutonvalidation.setText("VALIDER");
        boutonvalidation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonvalidationActionPerformed(evt);
            }
        });

        zonenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonenomActionPerformed(evt);
            }
        });

        jLabel1.setText("Entrer votre nom :");

        Cocabouton.setText("Bouteille Coca 33cl");
        Cocabouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CocaboutonActionPerformed(evt);
            }
        });

        OasisBouton.setText("Boutielle Oasis");
        OasisBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OasisBoutonActionPerformed(evt);
            }
        });

        IceTeaBouton.setText("Bouteille Ice tea");
        IceTeaBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IceTeaBoutonActionPerformed(evt);
            }
        });

        ValidationAchat.setText("Valider les achats");
        ValidationAchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidationAchatActionPerformed(evt);
            }
        });

        SUIVANT.setText("SUIVANT");
        SUIVANT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUIVANTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zonenom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(boutonvalidation)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texteresultat, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textselectionachat, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cocabouton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OasisBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IceTeaBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SUIVANT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ValidationAchat, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(Panier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(zonenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonvalidation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texteresultat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SUIVANT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textselectionachat, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(ValidationAchat))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(Cocabouton)
                                .addGap(18, 18, 18)
                                .addComponent(OasisBouton)
                                .addGap(18, 18, 18)
                                .addComponent(IceTeaBouton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(Panier, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonvalidationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonvalidationActionPerformed
        String NomUser= zonenom.getText(); //stockage du texte de l'utilisateur dans varaible nom user
        texteresultat.setText("Bonjour " + NomUser);
        SUIVANT.setVisible(true);

// TODO add your handling code here:
        
    }//GEN-LAST:event_boutonvalidationActionPerformed

    private void zonenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonenomActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_zonenomActionPerformed

    private void CocaboutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CocaboutonActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_CocaboutonActionPerformed

    private void OasisBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OasisBoutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OasisBoutonActionPerformed

    private void IceTeaBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IceTeaBoutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IceTeaBoutonActionPerformed

    private void ValidationAchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidationAchatActionPerformed
        String NomUser= zonenom.getText();
        Panier.setText("Merci pour vos achats " + NomUser);
// TODO add your handling code here:
    }//GEN-LAST:event_ValidationAchatActionPerformed

    private void SUIVANTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUIVANTActionPerformed
        textselectionachat.setText("Sélectionner ce que vous souhaitez acheter :");
        Cocabouton.setVisible(true);
        IceTeaBouton.setVisible(true);
        OasisBouton.setVisible(true);
        ValidationAchat.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SUIVANTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetreprincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetreprincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetreprincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetreprincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetreprincipale().setVisible(true);
            }
        });
        System.out.println("hello lancement de la fenetre");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cocabouton;
    private javax.swing.JRadioButton IceTeaBouton;
    private javax.swing.JRadioButton OasisBouton;
    private javax.swing.JLabel Panier;
    private javax.swing.JButton SUIVANT;
    private javax.swing.JButton ValidationAchat;
    private javax.swing.JButton boutonvalidation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel texteresultat;
    private javax.swing.JLabel textselectionachat;
    private javax.swing.JTextField zonenom;
    // End of variables declaration//GEN-END:variables
}
